#cloud-config

# Install Docker on an Ubuntu-based instance:
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups:
      - docker
      - sudo
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    hashed_passwd: ${user_password_hash} # To set passwd for an existing user
    lock_passwd: false # Allow login with password for serial console access

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - ufw
  - unattended-upgrades

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "local"
      }
  - path: /etc/ssh/sshd_config.d/cloud-init.conf
    # NOTE: Assumes the default user is 'ubuntu'
    content: |
      AllowAgentForwarding no
      AllowTcpForwarding no
      AllowUsers ubuntu
      AuthenticationMethods publickey
      KbdInteractiveAuthentication no
      MaxAuthTries 3
      PasswordAuthentication no
      PermitRootLogin no
      Port ${ssh_port}
      Protocol 2
      X11Forwarding no

runcmd:
  # Install Docker 
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker
  # Configure UFW
  - ufw allow ${ssh_port}/tcp
  - ufw enable
  # Configure sshd
  - systemctl restart sshd

final_message: "The system is finally up, after $UPTIME seconds"
